import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import assert from 'node:assert/strict';

const PACKAGE = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CLI = join(PACKAGE, 'bin', 'kairos-design.mjs');

function run(args, appDir) {
  try {
    return {
      code: 0,
      out: execFileSync('node', [CLI, ...args, ...(appDir ? ['--app', appDir] : [])], {
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'pipe'],
      }),
    };
  } catch (e) {
    return { code: e.status, out: (e.stdout ?? '') + (e.stderr ?? '') };
  }
}

/** A throwaway app with a config and, optionally, a file to inline into. */
function app({ targets, inlineHost = false }) {
  const dir = mkdtempSync(join(tmpdir(), 'kairos-app-'));
  mkdirSync(join(dir, 'public'), { recursive: true });
  writeFileSync(join(dir, 'kairos-design.json'), JSON.stringify({ targets }, null, 2));
  if (inlineHost) {
    writeFileSync(
      join(dir, 'index.html'),
      '<style>\n/* kairos-design:tokens begin */\n/* kairos-design:tokens end */\n</style>\n'
    );
  }
  return dir;
}

const CSS_TARGET = [{ artifact: 'kairos.css', path: 'public/kairos.css' }];

test('emit writes the artifact', () => {
  const dir = app({ targets: CSS_TARGET });
  const { code, out } = run(['emit'], dir);

  assert.equal(code, 0);
  assert.match(out, /\+ public\/kairos\.css/);

  const written = readFileSync(join(dir, 'public/kairos.css'), 'utf8');
  assert.match(written, /Generated by kairos-design/);
  assert.match(written, /kairos-state-chip/, 'the vocabulary came across');
});

test('the header names the version and says not to commit it', () => {
  const dir = app({ targets: CSS_TARGET });
  run(['emit'], dir);

  const { version } = JSON.parse(readFileSync(join(PACKAGE, 'package.json'), 'utf8'));
  const written = readFileSync(join(dir, 'public/kairos.css'), 'utf8');
  assert.match(written, new RegExp(`kairos-design ${version.replace(/\./g, '\\.')}`));
  assert.match(written, /not commit/);
});

test('emit writes no lockfile', () => {
  const dir = app({ targets: CSS_TARGET });
  run(['emit'], dir);
  // Nothing to lock: the version lives in the app's package.json, and the
  // output is rebuilt from it rather than tracked.
  assert.throws(() => readFileSync(join(dir, 'kairos-design.lock.json')), /ENOENT/);
});

test('emit is idempotent', () => {
  const dir = app({ targets: CSS_TARGET });
  run(['emit'], dir);
  const first = readFileSync(join(dir, 'public/kairos.css'), 'utf8');

  const { out } = run(['emit'], dir);
  assert.match(out, /= public\/kairos\.css/);
  assert.equal(readFileSync(join(dir, 'public/kairos.css'), 'utf8'), first);
});

test('dry run reports changes and writes nothing', () => {
  const dir = app({ targets: CSS_TARGET });
  const { code, out } = run(['emit', '--dry-run'], dir);

  assert.equal(code, 0);
  assert.match(out, /would change/);
  assert.throws(() => readFileSync(join(dir, 'public/kairos.css')), /ENOENT/);
});

test('an inline target replaces only the marked region', () => {
  const dir = app({
    targets: [{ artifact: 'tokens.css', path: 'index.html', inline: 'tokens' }],
    inlineHost: true,
  });
  const { code } = run(['emit'], dir);
  assert.equal(code, 0);

  const html = readFileSync(join(dir, 'index.html'), 'utf8');
  assert.match(html, /^<style>/, 'content before the marker survives');
  assert.match(html, /<\/style>\n$/, 'content after the marker survives');
  assert.match(html, /--kairos-bg: #fff8eb/, 'the tokens landed');
  assert.equal(html.match(/kairos-design:tokens begin/g).length, 1, 'markers are not duplicated');

  run(['emit'], dir);
  assert.equal(readFileSync(join(dir, 'index.html'), 'utf8'), html, 'emitting twice is idempotent');
});

test('an inline target without markers explains how to add them', () => {
  const dir = app({ targets: [{ artifact: 'tokens.css', path: 'index.html', inline: 'tokens' }] });
  writeFileSync(join(dir, 'index.html'), '<style></style>\n');

  const { code, out } = run(['emit'], dir);
  assert.equal(code, 1);
  assert.match(out, /kairos-design:tokens begin/);
});

test('an unknown artifact is rejected by name', () => {
  const dir = app({ targets: [{ artifact: 'nope.css', path: 'public/nope.css' }] });
  const { code, out } = run(['emit'], dir);
  assert.equal(code, 1);
  assert.match(out, /unknown artifact "nope\.css"/);
  assert.match(out, /tokens\.css/, 'the error lists what is available');
});

test('the artifact list is derived from dist, not hand-maintained', () => {
  // A component added to dist/ is known to the CLI with no second edit. The
  // old hardcoded array was a mirror of this directory that had to be updated
  // by hand, and a component missing from it was invisible to every app.
  const dir = app({ targets: [{ artifact: 'nope.css', path: 'public/nope.css' }] });
  const { out } = run(['emit'], dir);
  for (const expected of ['tokens.css', 'base.css', 'kairos.css', 'react/Button.tsx']) {
    assert.match(out, new RegExp(expected.replace(/[./]/g, '\\$&')));
  }
});

test('emitting TypeScript is refused, and says to import it instead', () => {
  const dir = app({ targets: [{ artifact: 'react/Button.tsx', path: 'src/ui/Button.tsx' }] });
  const { code, out } = run(['emit'], dir);
  assert.equal(code, 1);
  assert.match(out, /TypeScript/);
  assert.match(out, /kairos-design\/react/);
});

test('a missing config points at importing the package', () => {
  const dir = mkdtempSync(join(tmpdir(), 'kairos-app-'));
  const { code, out } = run(['emit'], dir);
  assert.equal(code, 1);
  assert.match(out, /kairos-design\.json/);
  assert.match(out, /@import "kairos-design\/tokens\.css"/);
});

test('the package refuses to emit into itself', () => {
  const { code, out } = run(['emit'], PACKAGE);
  assert.equal(code, 1);
  assert.match(out, /cannot emit into itself/);
});

test('sync and check explain where they went', () => {
  for (const gone of ['sync', 'check']) {
    const dir = app({ targets: CSS_TARGET });
    const { code, out } = run([gone], dir);
    assert.equal(code, 1, `${gone} exits non-zero`);
    assert.match(out, /npm install kairos-design/);
    assert.match(out, /kairos-design\.lock\.json/, 'it says to delete the lockfile');
  }
});
