import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, appendFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import assert from 'node:assert/strict';

const REGISTRY = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CLI = join(REGISTRY, 'bin', 'kairos-design.mjs');

function run(args, appDir) {
  try {
    return {
      code: 0,
      out: execFileSync('node', [CLI, ...args, '--app', appDir, '--registry', REGISTRY], {
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'pipe'],
      }),
    };
  } catch (e) {
    return { code: e.status, out: (e.stdout ?? '') + (e.stderr ?? '') };
  }
}

/** A throwaway app with a config and, optionally, a file to inline into. */
function app({ targets, inlineHost = false }) {
  const dir = mkdtempSync(join(tmpdir(), 'kairos-app-'));
  mkdirSync(join(dir, 'src'), { recursive: true });
  writeFileSync(join(dir, 'kairos-design.json'), JSON.stringify({ targets }, null, 2));
  if (inlineHost) {
    writeFileSync(
      join(dir, 'index.html'),
      '<style>\n/* kairos-design:tokens begin */\n/* kairos-design:tokens end */\n</style>\n'
    );
  }
  return dir;
}

const CSS_TARGET = [{ artifact: 'kairos.css', path: 'src/kairos.css' }];

test('sync writes the artifact and a lockfile', () => {
  const dir = app({ targets: CSS_TARGET });
  const { code, out } = run(['sync'], dir);

  assert.equal(code, 0);
  assert.match(out, /\+ src\/kairos\.css/);

  const written = readFileSync(join(dir, 'src/kairos.css'), 'utf8');
  assert.match(written, /Generated by kairos-design/);
  assert.match(written, /kairos-state-chip/, 'the vocabulary came across');

  const lock = JSON.parse(readFileSync(join(dir, 'kairos-design.lock.json'), 'utf8'));
  assert.match(lock.targets['src/kairos.css'], /^sha256:[0-9a-f]{64}$/);
});

test('check passes immediately after a sync', () => {
  const dir = app({ targets: CSS_TARGET });
  run(['sync'], dir);

  const { code, out } = run(['check'], dir);
  assert.equal(code, 0);
  assert.match(out, /Up to date/);
});

test('check fails when a vendored file was edited in place', () => {
  const dir = app({ targets: CSS_TARGET });
  run(['sync'], dir);
  appendFileSync(join(dir, 'src/kairos.css'), '/* local tweak */\n');

  const { code, out } = run(['check'], dir);
  assert.equal(code, 1);
  assert.match(out, /edited in place/);
  assert.doesNotMatch(out, /Behind the registry/, 'an edit is not reported as staleness');
});

test('check fails when the copy is missing', () => {
  const dir = app({ targets: CSS_TARGET });
  run(['sync'], dir);
  writeFileSync(join(dir, 'kairos-design.lock.json'), readFileSync(join(dir, 'kairos-design.lock.json')));
  execFileSync('rm', [join(dir, 'src/kairos.css')]);

  const { code, out } = run(['check'], dir);
  assert.equal(code, 1);
  assert.match(out, /missing/);
});

test('check without a lockfile says to sync first', () => {
  const dir = app({ targets: CSS_TARGET });
  const { code, out } = run(['check'], dir);
  assert.equal(code, 1);
  assert.match(out, /sync/);
});

test('dry run reports changes and writes nothing', () => {
  const dir = app({ targets: CSS_TARGET });
  const { code, out } = run(['sync', '--dry-run'], dir);

  assert.equal(code, 0);
  assert.match(out, /would change/);
  assert.throws(() => readFileSync(join(dir, 'src/kairos.css')), /ENOENT/);
  assert.throws(() => readFileSync(join(dir, 'kairos-design.lock.json')), /ENOENT/);
});

test('an inline target replaces only the marked region', () => {
  const dir = app({
    targets: [{ artifact: 'tokens.css', path: 'index.html', inline: 'tokens' }],
    inlineHost: true,
  });
  const { code } = run(['sync'], dir);
  assert.equal(code, 0);

  const html = readFileSync(join(dir, 'index.html'), 'utf8');
  assert.match(html, /^<style>/, 'content before the marker survives');
  assert.match(html, /<\/style>\n$/, 'content after the marker survives');
  assert.match(html, /--kairos-bg: #fff8eb/, 'the tokens landed');
  assert.equal(html.match(/kairos-design:tokens begin/g).length, 1, 'markers are not duplicated');

  run(['sync'], dir);
  const again = readFileSync(join(dir, 'index.html'), 'utf8');
  assert.equal(again, html, 'syncing twice is idempotent');
});

test('an inline target without markers explains how to add them', () => {
  const dir = app({
    targets: [{ artifact: 'tokens.css', path: 'index.html', inline: 'tokens' }],
  });
  writeFileSync(join(dir, 'index.html'), '<style></style>\n');

  const { code, out } = run(['sync'], dir);
  assert.equal(code, 1);
  assert.match(out, /kairos-design:tokens begin/);
});

test('an unknown artifact is rejected by name', () => {
  const dir = app({ targets: [{ artifact: 'nope.css', path: 'src/nope.css' }] });
  const { code, out } = run(['sync'], dir);
  assert.equal(code, 1);
  assert.match(out, /unknown artifact "nope\.css"/);
  assert.match(out, /tokens\.css/, 'the error lists what is available');
});

test('a missing config explains what to write', () => {
  const dir = mkdtempSync(join(tmpdir(), 'kairos-app-'));
  const { code, out } = run(['sync'], dir);
  assert.equal(code, 1);
  assert.match(out, /kairos-design\.json/);
  assert.match(out, /"targets"/);
});

test('the registry refuses to sync into itself', () => {
  const { code, out } = run(['sync'], REGISTRY);
  assert.equal(code, 1);
  assert.match(out, /cannot sync into itself/);
});

test('React components split across directories are refused', () => {
  const dir = app({
    targets: [
      { artifact: 'react/Dialog.tsx', path: 'src/ui/Dialog.tsx' },
      { artifact: 'react/ConfirmDialog.tsx', path: 'src/dialogs/ConfirmDialog.tsx' },
    ],
  });

  const { code, out } = run(['sync'], dir);
  assert.equal(code, 1);
  assert.match(out, /relative path/);
  // Otherwise this surfaces as a module-not-found at build time, a long way
  // from the config that caused it.
  assert.match(out, /src\/ui/);
  assert.match(out, /src\/dialogs/);
});

test('React components in one directory are fine', () => {
  const dir = app({
    targets: [
      { artifact: 'react/Dialog.tsx', path: 'src/ui/Dialog.tsx' },
      { artifact: 'react/ConfirmDialog.tsx', path: 'src/ui/ConfirmDialog.tsx' },
      { artifact: 'react/Button.tsx', path: 'src/ui/Button.tsx' },
    ],
  });

  const { code } = run(['sync'], dir);
  assert.equal(code, 0);
  assert.match(readFileSync(join(dir, 'src/ui/ConfirmDialog.tsx'), 'utf8'), /from '\.\/Dialog'/);
});
